const userActionTypes = {
   STORE_USER: 'STORE_USER',
   SET_STATUS: 'SET_STATUS',

   CHECK_USER_LOGGED_IN: 'CHECK_USER_LOGGED_IN',

   SIGN_IN: 'SIGN_IN',
   SIGN_OUT: 'SIGN_OUT',
   SIGN_UP: 'SIGN_UP',

   FORGET_PASSWORD: 'FORGET_PASSWORD',

   UPDATE_PASSWORD: 'UPDATE_PASSWORD',
};

export default userActionTypes;
