const userActionTypes = {
   STORE_USER: 'STORE_USER',
   SET_STATUS: 'SET_STATUS',

   CHECK_USER_LOGGED_IN: 'CHECK_USER_LOGGED_IN',

   SIGN_IN: 'SIGN_IN',
   SIGN_OUT: 'SIGN_OUT',
   SIGN_UP: 'SIGN_UP',

   FORGET_PASSWORD: 'FORGET_PASSWORD',
   CONFIRM_PASSWORD_RESET: 'CONFIRM_PASSWORD_RESET,',

   UPDATE_PASSWORD: 'UPDATE_PASSWORD',
   UPDATE_EMAIL: 'UPDATE_EMAIL',
   UPDATE_PROFILE: 'UPDATE_PROFILE',
};

export default userActionTypes;
